### ISSUE TITLE
Is it possible to install this app via Xcode without Apple certificate?

### ISSUE THREAD

**Issue by avlysenko** [bikkelbroeders/TouchBarDemoApp#11]
When compiling throws two or three errors:
The operation couldn’t be completed. Unable to log in with account ''. The login details for account '' were rejected.
No profiles for 'com.bikkelbroeders.TouchBarClient' were found:  Xcode couldn't find a provisioning profile matching 'com.bikkelbroeders.TouchBarClient'.
Code signing is required for product type 'Application' in SDK 'iOS 10.1'

***

Perhaps there is a less bloody way to install? :-)

**Comment by robbertkl** [comment]
In order to run an app on your iOS device, the app needs to be signed. We can't upload a signed version without going through the App Store. Fortunately, Apple now supports sideloading without the need for a paid developer account.

Please follow [these instructions](http://bouk.co/blog/sideload-iphone/) for sideloading.
