### ISSUE TITLE
Touchbar via Raspberry

### ISSUE THREAD

**Issue by jappyjan** [bikkelbroeders/TouchBarDemoApp#110]
Hey,

this is actually more of a question than an issue...

I really love the Apple Touchbar on my Mac and would like to use it with an external Keyboard...
So i googled for external Touchbar but all i could find are Software Solutions (like this one) where the touchbar is either emulated on the mac itself or an an ios device...

Is it possible (i guess it is) to port this code to be run of a raspberry pi (or similar) connected to a touch display (maybe even an official touchbar display)?

If so, may you point me towards the interesting code parts (like communication between app and mac) in this repository?
I actually don't really know where to look for it... 

Kind regards,
Jan fom Germany

**Comment by robbertkl** [comment]
Yeah, that could work. However, the communication uses Apple tech, so you'd have to replace that. This app mainly consists of UI code and communications; the "touchbar part" is actually pretty simple, so it'd make more sense to start a new app using only that and building custom communication with the external device (sending frames to pi and touch events back).

Since this is out of scope for this project, I'll close the issue, but I'd love to hear from you if you've created a Raspberry Pi version!
