### ISSUE TITLE
Any way to make it work on a phone?

### ISSUE THREAD

**Issue by jaramire** [bikkelbroeders/TouchBarDemoApp#2]
Hello,
Is there any way to make this work on a phone using the entire screen. Meaning, not have it act like a long touch bar, but a couple of rows on the phone instead; something that wraps around on the last widget that fits on each row. I can see this as a nice way to work with a laptop and an iPhone attached.

**Comment by robbertkl** [comment]
Yes, technically this would be possible. However, because interaction with the Touch Bar includes dragging, we've decided not to cut up the bar into pieces. This way, we keep the Touch Bar experience as close to the real Touch Bar on the new MacBook Pro.

**Comment by b-** [comment]
Perhaps the bar could be scrolled, so one could drag, say, above or below it to go from one end to the other.

**Comment by robbertkl** [comment]
While the app would run on an iPhone, it's really meant for larger screens like the iPads. We have some plans for the leftover screen space (see #7), but for the time being we won't be optimizing it for iPhone use by showing only a part of the Touch Bar.

Of course, since the app is open source, you could create your own fork for an iPhone optimized version. @b-'s suggestion might turn out quite nicely.

I'm going to close this for now, as our focus is on larger screens / always showing the full Touch Bar.
