### ISSUE TITLE
[Feature] Trackpad above Touch Bar on iPad

### ISSUE THREAD

**Issue by ghost** [bikkelbroeders/TouchBarDemoApp#26]
It will be great if you add virtual trackpad on free space in app for iPad.

**Comment by AndreasVerhoeven** [comment]
As much as we would like to do this, there is no way on macOS to simulate trackpad input at the moment.

**Comment by par5ul1** [comment]
could [this](http://stackoverflow.com/questions/21082362/how-to-send-raw-multitouch-trackpad-data-under-mac-os-x) be of any help? Sorry if it's useless but I found this and thought maybe it would be useful.

**Comment by palxex** [comment]
@par5ul1 Just did a little research, seems its main propose is help you inject multi-touch event if you already got a OSX-supported multi-touch device - it means magic mouse/trackpad. For those who don't have either, the multitouch framework cannot even start working ( cannot get a valid MTDeviceRef - and all later works depends it ). To make it work, we'll need first emulate such a device, from driver level, to makes this framework thinks it exist to work; and then, all gestures still need be recognize by  coding by hand - currently only 2 finger swipe/pan/rotate implemented - since seems the magic mouse/trackpad hardware recognize them internally. And the framework seems being rewritten by mavericks, possible more reverse engine needed. Seems its would be a much bigger task than the whole project currently.

**Comment by gerwitz** [comment]
Not to beat a dead horse, but could a subset of "non-pointer" gestures be more reasonable?

My (probably very personal) scenario: I use a mouse but still reach to the trackpad for two-finger scroll and three-finger swipe-between-spaces.

Even if that's going too far, thanks for publishing this! I hope it will drive TouchBar emulation across other "use my iPad as a peripheral" apps.
