### ISSUE TITLE
[Feature] - fn key diff

### ISSUE THREAD

**Issue by fernandocani** [bikkelbroeders/TouchBarDemoApp#29]
Some way to the macOS app identifies when the FN key was pressed to dismiss the TouchBar, or activate the FN options from the system.

**Comment by AndreasVerhoeven** [comment]
try `shift` + `FN`

**Comment by ajburns651** [comment]
Where is the option in settings to have it so that you hold fn and then lets say f7 to do the action, instead of just pressing it.

**Comment by AndreasVerhoeven** [comment]
That's not there: this is just a demo app, not a fully featured application

**Comment by AndreasVerhoeven** [comment]
If you keep on pressing `FN` btw, the Touch Bar will no disappear: it will only disappear **after** you released the `FN` key

**Comment by fernandocani** [comment]
Andreas, i got that only disappear when released, but that's what i'm suggesting, if you hold for 2-3 secs and than release, it not dismiss the TouchBar, only if pressed normaly.

**Comment by ajburns651** [comment]
there used to be a setting in mac os before searia, and it was under keyboard but now it's not their so I cant change it back.

**Comment by robbertkl** [comment]
We've just fixed this. Touch Bar toggles will now be ignored if:
- A mouse click arrives during the toggle key keypress
- The keypress takes too long (holding down the toggle key instead of pressing it)

Build the latest TouchBarServer from source code, or wait for the next release (1.6) which will include these improvements.
