### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by leo98gomez** [bikkelbroeders/TouchBarDemoApp#30]
Could it be possible to resize TouchBar when installed on iPad? or/and be able to move it around and be able to put it on the center of the screen?
Also could it be possible to pair through Bluetooth as an option? thanks

**Comment by matthijsotterloo** [comment]
That would be a weird idea since on the MacBook the TouchBar is right above your keyboard.

**Comment by MarcoBrandao** [comment]
What a lovely app to make. Thank you guys for your skills and to make possible to us, older MacBook Pro users, the ability to have an idea on how great Touch Bar is. I think it just made bigger my desire to buy a new MacBook Pro as soon as po$$ible.

I have two wishes/requests, one is the ability to have the toolbar fit my display from side to side. My MacBook is not retina ready, so it should be possible to use it on retina and non retina screens.

The second wish is to have it on a split part of the screen, because like that it would not be over my dock. For example, we would have the main screen in a 1280x700 resolution and the toolbar in a split screen with 1280x100. The dock would be right above and free.

If it is not possible, click and drag also could be nice.

Congratulation for the great work done until now.

**Comment by MarcoBrandao** [comment]
I would like to see a Check for Update option at the app Menu.

**Comment by robbertkl** [comment]
Please note this is not a generic suggestion/request issue. Please submit separate issues (with an _appropriate title_) for each suggestion or idea, after you search the issues list to see if it's there already, of course.

Closing this issue now.

@leo98gomez Touch Bar alignment options for remote Touch Bar clients are now included in the [latest release](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/latest)! As for bluetooth: there are already open issues about WiFi/bluetooth. However, performance would be lacking so we chose not to do this.
