### ISSUE TITLE
Pls support Elan Touchscreen

### ISSUE THREAD

**Issue by sonvirgo** [bikkelbroeders/TouchBarDemoApp#35]
I have an Elan Touchscreen and it works fine with 10.11.6 and 10.12.1 12B5657
Pls support
https://youtu.be/1FbQMclR82Y

BTW: very promising .... 
Pls make it fully function
https://youtu.be/lso3yaW1k3E

**Comment by midi1996** [comment]
You may need UPDD's driver + UPDD Gestures, will cost you a lot though. I'm using my Ativ tab 7 with macOS with touch and all that stuff and it's working fine :)

**Comment by sonvirgo** [comment]
Yet touch-base has evaluation driver, work greet with my Yoga 15

**Comment by robbertkl** [comment]
We "support" only official Mac devices that don't come with a Touch Bar. For unsupported devices, you're on your own. We just can't support this devices since we don't own them and can't test for them and don't even know what's broken.

Even though we don't support these devices, we're willing to include fixes for these devices when submitted through a PR, as long as they don't break functionality on supported devices.

**Comment by sonvirgo** [comment]
The touchscreen work exactly as if the real touch bar.

**Comment by robbertkl** [comment]
OK, so then there is no issue?

**Comment by sonvirgo** [comment]
I haven't retried iTunes again. But if the Touchbar is oded as is default on real Mac, I can test
