### ISSUE TITLE
fn toggle to show touch bar conflicts with macOS fn toggle to show fn keys.

### ISSUE THREAD

**Issue by cgdmnky** [bikkelbroeders/TouchBarDemoApp#51]
So I have the onscreen touchbar just where i like it. I want to press fn key to show the F1-F9 keys on the onscreen touchbar. I can hold down the fn key to see them but releasing the button will trigger your code to hide the onscreen touchbar.

**Comment by robbertkl** [comment]
Actually, after holding down Fn, as soon as your click one of the F1-F12 keys, the Touch Bar toggling is cancelled. This means that if you:
1. hold Fn
2. click F1 on the Touch Bar
3. release Fn

then the Touch Bar will _not_ disappear.

That being said, we will make some changes soon like adding a timeout on holding the Fn key so that the Touch Bar only toggles when it will be pressed quickly, like a normal keypress. That should help your situation if you just want to look at the function row, but you're not actually pressing one of the F-keys.

**Comment by cgdmnky** [comment]
Sounds good. Thanks for the response.

**Comment by robbertkl** [comment]
We've just fixed this. Touch Bar toggles will now be ignored if:
- A mouse click arrives during the toggle key keypress
- The keypress takes too long (holding down the toggle key instead of pressing it)

Build the latest TouchBarServer from source code, or wait for the next release (1.6) which will include these fixes.
