### ISSUE TITLE
Display bug on the Touchbar app

### ISSUE THREAD

**Issue by Fetiz** [bikkelbroeders/TouchBarDemoApp#57]
When I update the touchbarserver to 1.5 and use iPad  Air 2 to active all the features, the virtual keyboard display seems been cut off.
I tried to change the align setting, doesn't work.
Please check.
![img_0182](https://cloud.githubusercontent.com/assets/20578132/20371044/128e8408-ac9d-11e6-964e-a40b343283eb.PNG)

**Comment by moriwang** [comment]
I meet the same problem.

**Comment by robbertkl** [comment]
Unfortunately, this is a know iOS bug with the webview we're using for the keyboard. It usually happens when rotating your device. Force quit the app and restart it when the iPad is rotated to the orientation you want to use it in, and it should be fine again.

We know a possible fix for this, but it's gonna take some time.

**Comment by robbertkl** [comment]
Fixed in the [latest release](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/latest)!
